language: node_js
node_js:
  # LTS version
  - "8.0"
cache:
  directories:
    - node_modules
  yarn: true
install:
  - yarn install
before_script:
  - export CI=false
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build
  target_branch: gh-pages
  on:
    branch: master